/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teclado;
//import Complejos.TerminoC;
import Polinomios.*;
import TipoNumero.Complejo;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author giselle
 */
public class Menu extends javax.swing.JFrame {
    Polinomio poli1 = new Polinomio();
    TerminoP term1= new TerminoP();
    Complejo complejo1;
    String resultado;
    private Object vt;
    
    /*Complejo Comp1 = new Complejo();
    TerminoC term2 = new TerminoC();
    private Object cmp;*/
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextReal = new javax.swing.JTextField();
        jButtonMasReal = new javax.swing.JButton();
        jButtonMenosReal = new javax.swing.JButton();
        jButtonMultReal = new javax.swing.JButton();
        jButtonDivReal = new javax.swing.JButton();
        jButtonAReal = new javax.swing.JButton();
        jButtonLimpiarReal = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextCoef = new javax.swing.JTextField();
        jTextVar = new javax.swing.JTextField();
        jTextExp = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonATermino = new javax.swing.JButton();
        jButtonAPoli = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        txtCoefReal = new javax.swing.JTextField();
        jButtonAñadirComplejo = new javax.swing.JButton();
        jButtonLimpiarComplejo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnMasComplejo = new javax.swing.JButton();
        btnMenosComplejo = new javax.swing.JButton();
        btnMultComplejo = new javax.swing.JButton();
        btnDivComplejo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCoefComplejo = new javax.swing.JTextField();
        Signo = new javax.swing.JComboBox<>();
        jTextResultado2 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel1.setText("KeyMath");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel2.setText("KeyMath");

        jTextReal.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 24)); // NOI18N
        jTextReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRealActionPerformed(evt);
            }
        });
        jTextReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextRealKeyTyped(evt);
            }
        });

        jButtonMasReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMasReal.setText("+");
        jButtonMasReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasRealActionPerformed(evt);
            }
        });

        jButtonMenosReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMenosReal.setText("-");
        jButtonMenosReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosRealActionPerformed(evt);
            }
        });

        jButtonMultReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMultReal.setText("*");
        jButtonMultReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultRealActionPerformed(evt);
            }
        });

        jButtonDivReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDivReal.setText("/");
        jButtonDivReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivRealActionPerformed(evt);
            }
        });

        jButtonAReal.setText("Añadir Real");
        jButtonAReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonARealActionPerformed(evt);
            }
        });

        jButtonLimpiarReal.setText("Limpiar");
        jButtonLimpiarReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarRealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jTextReal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButtonAReal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonLimpiarReal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMasReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMenosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMultReal)
                            .addComponent(jButtonDivReal))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextReal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMasReal)
                            .addComponent(jButtonMultReal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMenosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDivReal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAReal)
                    .addComponent(jButtonLimpiarReal))
                .addGap(34, 34, 34))
        );

        jTabbedPane3.addTab("General Reales", jPanel1);

        jTabbedPane1.addTab("Reales", jTabbedPane3);

        jTextCoef.setFont(new java.awt.Font("Droid Sans", 0, 36)); // NOI18N
        jTextCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCoefActionPerformed(evt);
            }
        });
        jTextCoef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCoefKeyTyped(evt);
            }
        });

        jTextVar.setFont(new java.awt.Font("Droid Serif", 3, 36)); // NOI18N
        jTextVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVarActionPerformed(evt);
            }
        });
        jTextVar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextVarKeyTyped(evt);
            }
        });

        jTextExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExpActionPerformed(evt);
            }
        });
        jTextExp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextExpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextCoef, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextVar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jTextVar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTextCoef, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButtonMas.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 37, Short.MAX_VALUE))
        );

        jButtonATermino.setText("Añadir término");
        jButtonATermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATerminoActionPerformed(evt);
            }
        });

        jButtonAPoli.setText("Agregar Polinomio");
        jButtonAPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPoliActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonATermino)
                .addGap(18, 18, 18)
                .addComponent(jButtonAPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonLimpiar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonATermino)
                    .addComponent(jButtonAPoli)
                    .addComponent(jButtonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Generar Polinomio", jPanel2);

        jTabbedPane1.addTab("Polinomios", jTabbedPane2);

        txtCoefReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCoefReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoefRealActionPerformed(evt);
            }
        });
        txtCoefReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoefRealKeyTyped(evt);
            }
        });

        jButtonAñadirComplejo.setText("Añadir Complejo");
        jButtonAñadirComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirComplejoActionPerformed(evt);
            }
        });

        jButtonLimpiarComplejo.setText("Limpiar");
        jButtonLimpiarComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarComplejoActionPerformed(evt);
            }
        });

        btnMasComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMasComplejo.setText("+");
        btnMasComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasComplejoActionPerformed(evt);
            }
        });

        btnMenosComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMenosComplejo.setText("-");
        btnMenosComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosComplejoActionPerformed(evt);
            }
        });

        btnMultComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMultComplejo.setText("*");
        btnMultComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultComplejoActionPerformed(evt);
            }
        });

        btnDivComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDivComplejo.setText("/");
        btnDivComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivComplejoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMasComplejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenosComplejo))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMultComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDivComplejo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasComplejo)
                    .addComponent(btnMenosComplejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDivComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMultComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel3.setText("i");

        txtCoefComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoefComplejoActionPerformed(evt);
            }
        });

        Signo.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        Signo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAñadirComplejo)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtCoefReal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonLimpiarComplejo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCoefComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)))
                .addGap(50, 50, 50)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCoefReal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCoefComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadirComplejo)
                    .addComponent(jButtonLimpiarComplejo))
                .addGap(31, 31, 31))
        );

        jTabbedPane4.addTab("Generar Complejo", jPanel6);

        jTabbedPane1.addTab("Complejo", jTabbedPane4);

        jTextResultado2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jTextResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jTextResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCoefActionPerformed

    private void jTextVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVarActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextVarActionPerformed

    private void jTextExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExpActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
           resultado= jTextResultado2.getText()+ "+";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
//        poli1.agregarResta();
//        jTextResultado.setText(poli1.getPolinomioF());
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonATerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATerminoActionPerformed
        // TODO add your handling code here:
        int coef, exp;
        ArrayList poli = new ArrayList();
        String var;
        coef= Integer.parseInt(jTextCoef.getText());
        var= jTextVar.getText();
        exp= Integer.parseInt(jTextExp.getText());
        term1.setCoeficiente(coef);
        term1.setVariable(var);
        term1.setExponente(exp);
        poli1.insertaFinal(term1);
        jTextCoef.setText(null);
        jTextVar.setText(null);
        jTextExp.setText(null);
        System.out.println();
        while(!poli1.vacio()){
            poli.add(poli1.eliminaInicio());
        }
//        System.out.println(complejo.toString());
        resultado= jTextResultado2.getText()+poli.toString();
        jTextResultado2.setText(resultado);
        poli1.imprimir();
    }//GEN-LAST:event_jButtonATerminoActionPerformed

    private void jButtonAPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPoliActionPerformed
        // TODO add your handling code here:
//        jTextResultado.setText(poli1.getPolinomioF());
    }//GEN-LAST:event_jButtonAPoliActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextCoefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCoefKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextCoefKeyTyped

    private void jTextVarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVarKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(!Character.isLetter(a) && a != KeyEvent.VK_SPACE && a != KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_jTextVarKeyTyped

    private void jButtonMasRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "+";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMasRealActionPerformed

    private void jTextRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRealActionPerformed

    private void jButtonARealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonARealActionPerformed
        // TODO add your handling code here:
        int real;
        
        real = Integer.parseInt(jTextReal.getText());
        
        jTextReal.setText(null);
        
       resultado= jTextResultado2.getText()+real;
       jTextResultado2.setText(resultado);
       
    }//GEN-LAST:event_jButtonARealActionPerformed

    private void jButtonLimpiarRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarRealActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarRealActionPerformed

    private void jButtonMenosRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "-";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMenosRealActionPerformed

    private void jButtonMultRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "*";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMultRealActionPerformed

    private void jButtonDivRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivRealActionPerformed
        // TODO add your handling code here:
                resultado= jTextResultado2.getText()+ "/";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonDivRealActionPerformed

    private void jTextRealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRealKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextRealKeyTyped

    private void btnMasComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "+";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnMasComplejoActionPerformed

    private void btnMenosComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "-";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnMenosComplejoActionPerformed

    private void btnMultComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "*";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnMultComplejoActionPerformed

    private void btnDivComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "/";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnDivComplejoActionPerformed

    private void jButtonLimpiarComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarComplejoActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarComplejoActionPerformed

    private void jButtonAñadirComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirComplejoActionPerformed
        // TODO add your handling code here:
        double real, complejo;
       // int ExpCom;
        
        //ExpCom = Integer.parseInt(jTextExpComplejo.getText());
        
        jTextResultado2.setText(txtCoefReal.getText() + Signo.getSelectedItem() + txtCoefComplejo.getText()+ "i");
       
        real= Double.parseDouble(txtCoefReal.getText());
        
        complejo = Double.parseDouble(txtCoefComplejo.getText());
       
        
        complejo1= new Complejo(real, complejo);
        
        
        
//        jTextCoefReal.setText(null);
//       // jTextExpComplejo.setText(null);
//        
////       resultado= jTextResultado2.getText()+varCom;
//       jTextResultado2.setText(resultado);
        
    }//GEN-LAST:event_jButtonAñadirComplejoActionPerformed

    private void jTextExpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextExpKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextExpKeyTyped

    private void txtCoefRealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoefRealKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtCoefRealKeyTyped

    private void txtCoefRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoefRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoefRealActionPerformed

    private void txtCoefComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoefComplejoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCoefComplejoActionPerformed

    private void SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Signo;
    private javax.swing.JButton btnDivComplejo;
    private javax.swing.JButton btnMasComplejo;
    private javax.swing.JButton btnMenosComplejo;
    private javax.swing.JButton btnMultComplejo;
    private javax.swing.JButton jButtonAPoli;
    private javax.swing.JButton jButtonAReal;
    private javax.swing.JButton jButtonATermino;
    private javax.swing.JButton jButtonAñadirComplejo;
    private javax.swing.JButton jButtonDivReal;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiarComplejo;
    private javax.swing.JButton jButtonLimpiarReal;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMasReal;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMenosReal;
    private javax.swing.JButton jButtonMultReal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextCoef;
    private javax.swing.JTextField jTextExp;
    private javax.swing.JTextField jTextReal;
    private javax.swing.JTextField jTextResultado;
    private javax.swing.JTextField jTextResultado2;
    private javax.swing.JTextField jTextVar;
    private javax.swing.JTextField txtCoefComplejo;
    private javax.swing.JTextField txtCoefReal;
    // End of variables declaration//GEN-END:variables
}
