/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teclado;
//import Complejos.TerminoC;
import Aritmetica.*;
import Polinomios.*;
import TipoNumero.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author giselle
 */
public class Menu extends javax.swing.JFrame {
    DequeListaDoble TerminoActual= new DequeListaDoble();
    DequeListaDoble polinomioAcumulado= new DequeListaDoble();
    DequeListaDoble ListaPolinomios = new DequeListaDoble();
    TerminoP term1= new TerminoP();
    Complejo complejo1;
    String resultado;
    private Object vt;
    
    
    // RICARDO
    ArrayList<Complejo> listaComplejos;
    ArrayList<String> listOperaciones; // solamente guarda el caracter de la operacion.... + - * /...
    
    
    //******** END RICARDO
    
    /*Complejo Comp1 = new Complejo();
    TerminoC term2 = new TerminoC();
    private Object cmp;*/
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        listaComplejos = new ArrayList<Complejo>();
        listOperaciones = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextReal = new javax.swing.JTextField();
        jButtonAReal = new javax.swing.JButton();
        jButtonLimpiarReal = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButtonMasReal = new javax.swing.JButton();
        jButtonMultReal = new javax.swing.JButton();
        jButtonMenosReal = new javax.swing.JButton();
        jButtonDivReal = new javax.swing.JButton();
        jTextNumeros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextCoef = new javax.swing.JTextField();
        jTextVar = new javax.swing.JTextField();
        jTextExp = new javax.swing.JTextField();
        SignoPolinomios = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonATermino = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jTextPolinomioActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBtnAgregarPolinomio = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnMasComplejo = new javax.swing.JButton();
        btnMenosComplejo = new javax.swing.JButton();
        btnMultComplejo = new javax.swing.JButton();
        btnDivComplejo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtCoefReal = new javax.swing.JTextField();
        Signo = new javax.swing.JComboBox<>();
        txtCoefImaginario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButtonAñadirComplejo = new javax.swing.JButton();
        jButtonLimpiarComplejo = new javax.swing.JButton();
        jTextResultado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel1.setText("KeyMath");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel2.setText("KeyMath");

        jTextReal.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 24)); // NOI18N
        jTextReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRealActionPerformed(evt);
            }
        });
        jTextReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextRealKeyTyped(evt);
            }
        });

        jButtonAReal.setText("Añadir Real");
        jButtonAReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonARealActionPerformed(evt);
            }
        });

        jButtonLimpiarReal.setText("Limpiar");
        jButtonLimpiarReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarRealActionPerformed(evt);
            }
        });

        jButtonMasReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMasReal.setText("+");
        jButtonMasReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasRealActionPerformed(evt);
            }
        });

        jButtonMultReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMultReal.setText("*");
        jButtonMultReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultRealActionPerformed(evt);
            }
        });

        jButtonMenosReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMenosReal.setText("-");
        jButtonMenosReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosRealActionPerformed(evt);
            }
        });

        jButtonDivReal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDivReal.setText("/");
        jButtonDivReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivRealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMasReal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDivReal)
                    .addComponent(jButtonMultReal))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMasReal)
                    .addComponent(jButtonMultReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenosReal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivReal))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel6.setText("Números hasta ahora:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextReal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAReal)
                                .addGap(20, 20, 20)))
                        .addGap(35, 35, 35)
                        .addComponent(jButtonLimpiarReal)
                        .addGap(182, 182, 182)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextReal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAReal)
                            .addComponent(jButtonLimpiarReal)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane3.addTab("General Reales", jPanel1);

        jTabbedPane1.addTab("Reales", jTabbedPane3);

        jTextCoef.setFont(new java.awt.Font("Droid Sans", 0, 36)); // NOI18N
        jTextCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCoefActionPerformed(evt);
            }
        });
        jTextCoef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCoefKeyTyped(evt);
            }
        });

        jTextVar.setFont(new java.awt.Font("Droid Serif", 3, 36)); // NOI18N
        jTextVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVarActionPerformed(evt);
            }
        });
        jTextVar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextVarKeyTyped(evt);
            }
        });

        jTextExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExpActionPerformed(evt);
            }
        });
        jTextExp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextExpKeyTyped(evt);
            }
        });

        SignoPolinomios.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        SignoPolinomios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        SignoPolinomios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoPolinomiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(SignoPolinomios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCoef, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextVar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCoef, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jTextVar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(SignoPolinomios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))))
        );

        jButtonMas.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonATermino.setText("Añadir término");
        jButtonATermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATerminoActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButtonATermino)
                .addGap(186, 186, 186)
                .addComponent(jButtonLimpiar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonATermino)
                    .addComponent(jButtonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Polinomio actual:");

        jBtnAgregarPolinomio.setText("Agregar Polinomio");
        jBtnAgregarPolinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarPolinomioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAgregarPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextPolinomioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(201, 461, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jTextPolinomioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregarPolinomio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Generar Polinomio", jPanel2);

        jTabbedPane1.addTab("Polinomios", jTabbedPane2);

        btnMasComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMasComplejo.setText("+");
        btnMasComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasComplejoActionPerformed(evt);
            }
        });

        btnMenosComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMenosComplejo.setText("-");
        btnMenosComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosComplejoActionPerformed(evt);
            }
        });

        btnMultComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMultComplejo.setText("*");
        btnMultComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultComplejoActionPerformed(evt);
            }
        });

        btnDivComplejo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDivComplejo.setText("/");
        btnDivComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivComplejoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMasComplejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenosComplejo))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMultComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDivComplejo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasComplejo)
                    .addComponent(btnMenosComplejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivComplejo)
                    .addComponent(btnMultComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        txtCoefReal.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txtCoefReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoefRealActionPerformed(evt);
            }
        });
        txtCoefReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoefRealKeyTyped(evt);
            }
        });

        Signo.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        Signo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoActionPerformed(evt);
            }
        });

        txtCoefImaginario.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txtCoefImaginario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoefImaginarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel3.setText("i");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCoefReal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCoefImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoefReal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoefImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29))))
        );

        jButtonAñadirComplejo.setText("Añadir Complejo");
        jButtonAñadirComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirComplejoActionPerformed(evt);
            }
        });

        jButtonLimpiarComplejo.setText("Limpiar");
        jButtonLimpiarComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarComplejoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonAñadirComplejo)
                .addGap(71, 71, 71)
                .addComponent(jButtonLimpiarComplejo)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadirComplejo)
                    .addComponent(jButtonLimpiarComplejo))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Generar Complejo", jPanel6);

        jTabbedPane1.addTab("Complejo", jTabbedPane4);

        jTextResultado2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabel4.setText("RESULTADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCoefActionPerformed

    private void jTextVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVarActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextVarActionPerformed

    private void jTextExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExpActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
           resultado= jTextResultado2.getText()+ "+";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
//        poli1.agregarResta();
//        jTextResultado.setText(poli1.getPolinomioF());
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonATerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATerminoActionPerformed
        // TODO add your handling code here:
        int coef, exp;
        ArrayList poli = new ArrayList();//Almacena los términos que ya se agregaron
        String var;
        String signoP = String.valueOf(SignoPolinomios.getSelectedItem());
        
        coef= Integer.parseInt(signoP+jTextCoef.getText());
        var= jTextVar.getText();
        exp= Integer.parseInt(jTextExp.getText());
        term1.setCoeficiente(coef);
        term1.setVariable(var);
        term1.setExponente(exp);
        
        TerminoActual.insertFirst(term1);
        boolean flag = true;
        if(polinomioAcumulado.isEmpty()){
            flag = true;
        }
        else{
            flag = false;
        }
        polinomioAcumulado.insertFirst(term1);
        
        //Limpiando los cuadros
        jTextCoef.setText(null);
        jTextVar.setText(null);
        jTextExp.setText(null);
        
        
        while(!TerminoActual.isEmpty()){
            poli.add(TerminoActual.removeFirst());
        }
        
        String termino= poli.toString().substring(1, poli.toString().length()-1);
        
        if(flag==true)
         jTextPolinomioActual.setText(jTextPolinomioActual.getText()+termino);
        else
        jTextPolinomioActual.setText(jTextPolinomioActual.getText()+"+"+termino);

    }//GEN-LAST:event_jButtonATerminoActionPerformed

    private void jBtnAgregarPolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarPolinomioActionPerformed
        // TODO add your handling code here:
        ListaPolinomios.insertFirst(polinomioAcumulado);

    }//GEN-LAST:event_jBtnAgregarPolinomioActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextCoefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCoefKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextCoefKeyTyped

    private void jTextVarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVarKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(!Character.isLetter(a) && a != KeyEvent.VK_SPACE && a != KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_jTextVarKeyTyped

    private void jButtonMasRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "+";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMasRealActionPerformed

    private void jTextRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRealActionPerformed

    private void jButtonARealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonARealActionPerformed
        // TODO add your handling code here:
        double real;
        
        real = Integer.parseInt(jTextReal.getText());
        
        jTextReal.setText(null);
        
       resultado= jTextResultado2.getText()+real;
       jTextResultado2.setText(resultado);
       
    }//GEN-LAST:event_jButtonARealActionPerformed

    private void jButtonLimpiarRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarRealActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarRealActionPerformed

    private void jButtonMenosRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "-";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMenosRealActionPerformed

    private void jButtonMultRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultRealActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "*";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonMultRealActionPerformed

    private void jButtonDivRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivRealActionPerformed
        // TODO add your handling code here:
                resultado= jTextResultado2.getText()+ "/";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_jButtonDivRealActionPerformed

    private void jTextRealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRealKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextRealKeyTyped

    private void btnMasComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasComplejoActionPerformed
        // TODO add your handling code here:
        // RICARDO
        
        
        listOperaciones.add(" + ");
        
        String verText = recorrerListaComplejos();
        
        jTextResultado2.setText(verText);
    }//GEN-LAST:event_btnMasComplejoActionPerformed

    private void btnMenosComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "-";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnMenosComplejoActionPerformed

    private void btnMultComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "*";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnMultComplejoActionPerformed

    private void btnDivComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivComplejoActionPerformed
        // TODO add your handling code here:
        resultado= jTextResultado2.getText()+ "/";

        jTextResultado2.setText(resultado);
    }//GEN-LAST:event_btnDivComplejoActionPerformed

    private void jButtonLimpiarComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarComplejoActionPerformed
        // TODO add your handling code here:
        jTextResultado2.setText(null);
    }//GEN-LAST:event_jButtonLimpiarComplejoActionPerformed

    private void jButtonAñadirComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirComplejoActionPerformed
        // TODO add your handling code here:
         
        // RICARDO   
        
        String signo = String.valueOf(Signo.getSelectedItem());
        double real= Double.parseDouble(txtCoefReal.getText());
        double imaginario = Double.parseDouble(signo+txtCoefImaginario.getText());
        
        
        
        listaComplejos.add(new Complejo(real, imaginario));
        
        String verText = recorrerListaComplejos(); // devuelve concatenacion de todos los elementos ingresados
        
        jTextResultado2.setText(verText);
        
//        jTextCoefReal.setText(null);
//       // jTextExpComplejo.setText(null);
//        
////       resultado= jTextResultado2.getText()+varCom;
//       jTextResultado2.setText(resultado);
        
    }//GEN-LAST:event_jButtonAñadirComplejoActionPerformed

    private void jTextExpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextExpKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_jTextExpKeyTyped

    private void txtCoefRealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoefRealKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(a < '0' || a >   '9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtCoefRealKeyTyped

    private void txtCoefRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoefRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoefRealActionPerformed

    private void txtCoefImaginarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoefImaginarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCoefImaginarioActionPerformed

    private void SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignoActionPerformed

    private void SignoPolinomiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoPolinomiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignoPolinomiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // RICARDO ***********************************************
    private String recorrerListaComplejos()
    {
        String concatComplejos = ""; //cadena unicamente servible para mostrar info en pantalla mientras se va agregando mas complejos
        
        for(int i = 0; i < listaComplejos.size(); i++)
        {
            concatComplejos += listaComplejos.get(i).toString();
            if(listOperaciones.size() > i)
                concatComplejos += listOperaciones.get(i).toString();
        }
        return concatComplejos;
    }
    //**********************************************************
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Signo;
    private javax.swing.JComboBox<String> SignoPolinomios;
    private javax.swing.JButton btnDivComplejo;
    private javax.swing.JButton btnMasComplejo;
    private javax.swing.JButton btnMenosComplejo;
    private javax.swing.JButton btnMultComplejo;
    private javax.swing.JButton jBtnAgregarPolinomio;
    private javax.swing.JButton jButtonAReal;
    private javax.swing.JButton jButtonATermino;
    private javax.swing.JButton jButtonAñadirComplejo;
    private javax.swing.JButton jButtonDivReal;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiarComplejo;
    private javax.swing.JButton jButtonLimpiarReal;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMasReal;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMenosReal;
    private javax.swing.JButton jButtonMultReal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextCoef;
    private javax.swing.JTextField jTextExp;
    private javax.swing.JTextField jTextNumeros;
    private javax.swing.JTextField jTextPolinomioActual;
    private javax.swing.JTextField jTextReal;
    private javax.swing.JTextField jTextResultado;
    private javax.swing.JTextField jTextResultado2;
    private javax.swing.JTextField jTextVar;
    private javax.swing.JTextField txtCoefImaginario;
    private javax.swing.JTextField txtCoefReal;
    // End of variables declaration//GEN-END:variables
}
